# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-15 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import general.functions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('percent', models.DecimalField(decimal_places=5, default=0, max_digits=19)),
                ('value', models.DecimalField(decimal_places=5, default=1.0, max_digits=19)),
                ('short_title', models.CharField(max_length=10)),
                ('removed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('fin', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('', 'Hamısı'), ('man', 'Kişi'), ('woman', 'Qadın')], default='man', max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='ad günü')),
                ('id_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=general.functions.path_and_rename)),
                ('passport_picture1', models.ImageField(blank=True, null=True, upload_to=general.functions.path_and_rename)),
                ('passport_picture2', models.ImageField(blank=True, null=True, upload_to=general.functions.path_and_rename)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='notes', to='panel.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=10)),
                ('ip', models.CharField(max_length=255)),
                ('removed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('', 'Səbəb'), ('permit', 'İcaze'), ('late', 'Gecikmə'), ('penalty', 'Cərimə')], max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('day', models.IntegerField()),
                ('time', models.TimeField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('work_minute', models.IntegerField(default=0)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Miqdar')),
                ('result_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Miqdar')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Cərimə')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('reason', models.CharField(choices=[('income', 'Mədaxil'), ('outcome', 'Məxaric')], max_length=20)),
                ('type', models.CharField(choices=[('main', 'Əsas'), ('percent', 'Faiz'), ('office', 'Ofis')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Miqdar')),
                ('notes', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Currency')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('object', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeType2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.OutcomeName')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_number', models.CharField(max_length=255, verbose_name='Girov nomresi')),
                ('first_date', models.DateTimeField(blank=True, null=True, verbose_name='ilk tarix')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='son tarix')),
                ('notes', models.TextField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True, default='', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Miqdar')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Qalan miqdar')),
                ('total_debt_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Qalan Faiz')),
                ('status', models.CharField(choices=[('', 'Hamısı'), ('active', 'Aktiv'), ('waiting', 'Yoxlamada'), ('paided', 'Bağlandı'), ('ordered', '--- Sifarişə verildi'), ('closed', '--- Təhvil verildi'), ('saled', 'Satıldı')], default='', max_length=100)),
                ('annuitet', models.BooleanField(default=False)),
                ('product_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Miqdar')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='odeme tarixi')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delay_day', models.IntegerField(default=0, verbose_name='Gecikmə')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Currency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Customer')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Department')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDailyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackagePaymentDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_day', models.IntegerField(default=0, verbose_name='Gecikmə')),
                ('paid_date', models.DateTimeField(verbose_name='Odənilen tarix')),
                ('pay_date', models.DateTimeField(blank=True, null=True, verbose_name='Odənməli tarix')),
                ('month_count', models.IntegerField(default=0, verbose_name='Ay Sayı')),
                ('day_count', models.IntegerField(default=0, verbose_name='Gün Sayı')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Odənilən miqdar')),
                ('calculated_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Hesablanmış faiz')),
                ('paid_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Faiz miqdarı')),
                ('percent_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Faiz Borcu')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Miqdar')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=general.functions.path_and_rename)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('', '-- Paket növü --'), ('daily', 'Gündəlik'), ('ten-daily', '10 Gunluk')], max_length=255)),
                ('month_count', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('removed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('removed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Product')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Qalan miqdar')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Package')),
            ],
        ),
        migrations.AddField(
            model_name='packageproduct',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.ProductType'),
        ),
        migrations.AddField(
            model_name='package',
            name='packet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.PackageType'),
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Product'),
        ),
        migrations.AddField(
            model_name='package',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.ProductType'),
        ),
        migrations.AddField(
            model_name='outcomename',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.OutcomeType'),
        ),
        migrations.AddField(
            model_name='incomeoutcome',
            name='outcome_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.OutcomeName'),
        ),
        migrations.AddField(
            model_name='incomeoutcome',
            name='outcome_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.OutcomeType'),
        ),
        migrations.AddField(
            model_name='incomeoutcome',
            name='outcome_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.OutcomeType2'),
        ),
        migrations.AddField(
            model_name='incomeoutcome',
            name='package_payment_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.PackagePaymentDates'),
        ),
        migrations.AddField(
            model_name='incomeoutcome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomeoutcome',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together=set([('employee', 'month', 'year')]),
        ),
    ]
