# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepaymentdates',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Cərimə'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
