# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_auto_20190915_1834'),
        ('panel', '0001_initial'),
        ('base_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='panel.Department'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='qruplar'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='permissions_department',
            field=models.ManyToManyField(blank=True, null=True, related_name='_myuser_permissions_department_+', to='panel.Department'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='səlahiyyətləri'),
        ),
    ]
